- name: Create an ubuntu instance on Amazon EC2
  hosts: localhost
  tasks:
          - name: Get the ubuntu trusty ami
            ec2_ami_find:
                    name: "ubuntu/images/ebs/ubuntu-trusty-14.04-amd64-server-*"
            register: ami_find
          - name: start the instance
            ec2:
                    image: "{{ ami_find.results[0].ami_id}}"
                    instance_type: t2.micro
                    key_name: mykey
                    group: [web, ssh, outbound]
                    instance_tags: { type: web, env: testing }
                    wait: yes
